using IptvManagement.Application.Abstractions;
using IptvManagement.Application.DTOs;
using IptvManagement.Domain.Entities;
using IptvManagement.Domain.Enums;
using IptvManagement.Infrastructure.Data;
using IptvManagement.Infrastructure.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace IptvManagement.Infrastructure.Services;

public sealed class AdminDataService(AppDbContext db, IStreamUrlProtector protector, ITokenService tokens, IInvoiceService invoices, UserManager<ApplicationUser> users) : IAdminDataService
{
    public async Task<IReadOnlyList<Customer>> GetCustomersAsync(string? search, string? filter, CancellationToken ct)
    {
        var q = db.Customers.AsNoTracking().AsQueryable();
        if (!string.IsNullOrWhiteSpace(search)) q = q.Where(c => c.CustomerNumber.Contains(search) || c.FirstName.Contains(search) || c.LastName.Contains(search) || c.Email.Contains(search) || (c.CompanyName != null && c.CompanyName.Contains(search)));
        q = filter switch { "active" => q.Where(c => c.IsActive && !c.IsBlocked), "inactive" => q.Where(c => !c.IsActive), "blocked" => q.Where(c => c.IsBlocked), _ => q };
        return await q.OrderBy(c => c.CustomerNumber).Take(200).ToListAsync(ct);
    }
    public async Task SaveCustomerAsync(CustomerFormModel m, string? userId, CancellationToken ct) { var e = m.Id.HasValue ? await db.Customers.FindAsync([m.Id.Value], ct) : new Customer { CreatedAtUtc = DateTime.UtcNow }; if (e is null) return; e.CustomerNumber=m.CustomerNumber; e.FirstName=m.FirstName; e.LastName=m.LastName; e.CompanyName=m.CompanyName; e.Email=m.Email; e.Phone=m.Phone; e.Address=m.Address; e.PostalCode=m.PostalCode; e.City=m.City; e.Country=m.Country; e.Notes=m.Notes; e.IsActive=m.IsActive; e.IsBlocked=m.IsBlocked; e.UpdatedAtUtc=DateTime.UtcNow; if(!m.Id.HasValue) db.Customers.Add(e); db.AuditLogs.Add(new(){UserId=userId,Action=m.Id.HasValue?"Kunde geändert":"Kunde angelegt",EntityName=nameof(Customer),EntityId=e.Id.ToString()}); await db.SaveChangesAsync(ct); }
    public Task DeactivateCustomerAsync(Guid id, CancellationToken ct)=>Update<Customer>(id, c=>c.IsActive=false, "Kunde deaktiviert", ct); public Task SetCustomerBlockedAsync(Guid id,bool b,CancellationToken ct)=>Update<Customer>(id,c=>c.IsBlocked=b,b?"Kunde blockiert":"Kunde entsperrt",ct);

    public async Task<IReadOnlyList<ChannelCategory>> GetCategoriesAsync(CancellationToken ct)=>await db.Categories.AsNoTracking().OrderBy(c=>c.SortOrder).ToListAsync(ct);
    public async Task SaveCategoryAsync(CategoryFormModel m,CancellationToken ct){ var e=m.Id.HasValue?await db.Categories.FindAsync([m.Id.Value],ct):new ChannelCategory(); if(e is null)return; e.Name=m.Name; e.Description=m.Description; e.SortOrder=m.SortOrder; e.IsActive=m.IsActive; if(!m.Id.HasValue)db.Categories.Add(e); db.AuditLogs.Add(new(){Action=m.Id.HasValue?"Kategorie geändert":"Kategorie angelegt",EntityName=nameof(ChannelCategory),EntityId=e.Id.ToString()}); await db.SaveChangesAsync(ct);} public Task DeactivateCategoryAsync(Guid id,CancellationToken ct)=>Update<ChannelCategory>(id,c=>c.IsActive=false,"Kategorie deaktiviert",ct);

    public async Task<IReadOnlyList<SubscriptionPackage>> GetPackagesAsync(CancellationToken ct)=>await db.Packages.Include(p=>p.PackageChannels).AsNoTracking().OrderBy(p=>p.Name).ToListAsync(ct);
    public async Task SavePackageAsync(PackageFormModel m,CancellationToken ct){ var e=m.Id.HasValue?await db.Packages.Include(p=>p.PackageChannels).FirstOrDefaultAsync(p=>p.Id==m.Id.Value,ct):new SubscriptionPackage{CreatedAtUtc=DateTime.UtcNow}; if(e is null)return; e.Name=m.Name; e.Description=m.Description; e.Price=m.Price; e.Currency=m.Currency; e.DurationInMonths=m.DurationInMonths; e.MaxDevices=m.MaxDevices; e.IsActive=m.IsActive; e.UpdatedAtUtc=DateTime.UtcNow; e.PackageChannels.Clear(); foreach(var id in m.ChannelIds.Distinct()) e.PackageChannels.Add(new(){Package=e,ChannelId=id}); if(!m.Id.HasValue)db.Packages.Add(e); db.AuditLogs.Add(new(){Action=m.Id.HasValue?"Paket geändert":"Paket angelegt",EntityName=nameof(SubscriptionPackage),EntityId=e.Id.ToString()}); await db.SaveChangesAsync(ct);} public Task DeactivatePackageAsync(Guid id,CancellationToken ct)=>Update<SubscriptionPackage>(id,p=>p.IsActive=false,"Paket deaktiviert",ct);

    public async Task<IReadOnlyList<Channel>> GetChannelsAsync(CancellationToken ct)=>await db.Channels.Include(c=>c.Category).AsNoTracking().OrderBy(c=>c.SortOrder).ToListAsync(ct);
    public async Task SaveChannelAsync(ChannelFormModel m,CancellationToken ct){ var e=m.Id.HasValue?await db.Channels.FindAsync([m.Id.Value],ct):new Channel{CreatedAtUtc=DateTime.UtcNow}; if(e is null)return; e.Name=m.Name; e.Description=m.Description; if(!string.IsNullOrWhiteSpace(m.StreamUrl)) e.StreamUrlEncrypted=protector.Protect(m.StreamUrl); e.LogoUrl=m.LogoUrl; e.CategoryId=m.CategoryId; e.CountryCode=m.CountryCode; e.LanguageCode=m.LanguageCode; e.SortOrder=m.SortOrder; e.IsActive=m.IsActive; e.IsPubliclyAvailable=m.IsPubliclyAvailable; e.LicenseReference=m.LicenseReference; e.LicenseValidUntilUtc=m.LicenseValidUntilUtc; e.UpdatedAtUtc=DateTime.UtcNow; if(!m.Id.HasValue)db.Channels.Add(e); db.AuditLogs.Add(new(){Action=m.Id.HasValue?"Sender geändert":"Sender angelegt",EntityName=nameof(Channel),EntityId=e.Id.ToString()}); await db.SaveChangesAsync(ct);} public Task DeactivateChannelAsync(Guid id,CancellationToken ct)=>Update<Channel>(id,c=>c.IsActive=false,"Sender deaktiviert",ct); public async Task<bool> TestStreamAsync(string url,CancellationToken ct){ using var http=new HttpClient{Timeout=TimeSpan.FromSeconds(5)}; try{ using var response=await http.SendAsync(new HttpRequestMessage(HttpMethod.Head,url),ct); return response.IsSuccessStatusCode;}catch{return false;} }

    public async Task<IReadOnlyList<Subscription>> GetSubscriptionsAsync(CancellationToken ct)=>await db.Subscriptions.Include(s=>s.Customer).Include(s=>s.Package).AsNoTracking().OrderByDescending(s=>s.CreatedAtUtc).ToListAsync(ct);
    public async Task SaveSubscriptionAsync(SubscriptionFormModel m,CancellationToken ct){ var e=m.Id.HasValue?await db.Subscriptions.FindAsync([m.Id.Value],ct):new Subscription{CreatedAtUtc=DateTime.UtcNow}; if(e is null)return; e.CustomerId=m.CustomerId; e.PackageId=m.PackageId; e.SubscriptionNumber=string.IsNullOrWhiteSpace(m.SubscriptionNumber)?$"SUB-{DateTime.UtcNow:yyyyMMddHHmmss}":m.SubscriptionNumber; e.StartDateUtc=m.StartDateUtc; e.ExpirationDateUtc=m.StartDateUtc.AddMonths(m.DurationInMonths); e.Status=m.Status; e.MaxDevices=m.MaxDevices; e.AutomaticRenewal=m.AutomaticRenewal; e.UpdatedAtUtc=DateTime.UtcNow; if(!m.Id.HasValue)db.Subscriptions.Add(e); db.AuditLogs.Add(new(){Action=m.Id.HasValue?"Abonnement geändert":"Abonnement angelegt",EntityName=nameof(Subscription),EntityId=e.Id.ToString()}); await db.SaveChangesAsync(ct);} public Task SetSubscriptionStatusAsync(Guid id,SubscriptionStatus s,CancellationToken ct)=>Update<Subscription>(id,x=>x.Status=s,$"Abonnementstatus {s}",ct); public async Task RenewSubscriptionAsync(Guid id,int months,CancellationToken ct){ var e=await db.Subscriptions.FindAsync([id],ct); if(e is null)return; e.Renew(months,DateTime.UtcNow); db.AuditLogs.Add(new(){Action=$"Abonnement um {months} Monate verlängert",EntityName=nameof(Subscription),EntityId=id.ToString()}); await db.SaveChangesAsync(ct);} public async Task<string> IssueTokenAsync(Guid id,CancellationToken ct){ var token=tokens.CreateSecureToken(); var e=await db.Subscriptions.FindAsync([id],ct); if(e is null)return ""; e.PlaylistTokenHash=tokens.HashToken(token); e.TokenCreatedAtUtc=DateTime.UtcNow; db.AuditLogs.Add(new(){Action="Token erstellt",EntityName=nameof(Subscription),EntityId=id.ToString()}); await db.SaveChangesAsync(ct); return token;} public Task RevokeTokenAsync(Guid id,CancellationToken ct)=>Update<Subscription>(id,s=>s.PlaylistTokenHash=null,"Token widerrufen",ct);

    public async Task<IReadOnlyList<Device>> GetDevicesAsync(CancellationToken ct)=>await db.Devices.Include(d=>d.Customer).Include(d=>d.Subscription).AsNoTracking().OrderBy(d=>d.DeviceName).ToListAsync(ct);
    public async Task SaveDeviceAsync(DeviceFormModel m,CancellationToken ct){ var e=m.Id.HasValue?await db.Devices.FindAsync([m.Id.Value],ct):new Device{FirstSeenAtUtc=DateTime.UtcNow}; if(e is null)return; e.CustomerId=m.CustomerId; e.SubscriptionId=m.SubscriptionId; e.DeviceName=m.DeviceName; e.DeviceIdentifierHash=tokens.HashToken(m.DeviceIdentifier); e.DeviceType=m.DeviceType; e.IsActive=m.IsActive; e.IsBlocked=m.IsBlocked; if(!m.Id.HasValue)db.Devices.Add(e); db.AuditLogs.Add(new(){Action=m.Id.HasValue?"Gerät geändert":"Gerät aktiviert",EntityName=nameof(Device),EntityId=e.Id.ToString()}); await db.SaveChangesAsync(ct);} public Task SetDeviceBlockedAsync(Guid id,bool b,CancellationToken ct)=>Update<Device>(id,d=>d.IsBlocked=b,b?"Gerät blockiert":"Gerät entsperrt",ct); public Task DeactivateDeviceAsync(Guid id,CancellationToken ct)=>Update<Device>(id,d=>d.IsActive=false,"Gerät deaktiviert",ct);

    public async Task<IReadOnlyList<Payment>> GetPaymentsAsync(CancellationToken ct)=>await db.Payments.AsNoTracking().OrderByDescending(p=>p.PaymentDateUtc).ToListAsync(ct); public async Task SavePaymentAsync(PaymentFormModel m,CancellationToken ct){ var e=m.Id.HasValue?await db.Payments.FindAsync([m.Id.Value],ct):new Payment{CreatedAtUtc=DateTime.UtcNow}; if(e is null)return; e.CustomerId=m.CustomerId; e.SubscriptionId=m.SubscriptionId; e.PaymentNumber=string.IsNullOrWhiteSpace(m.PaymentNumber)?$"ZA-{DateTime.UtcNow:yyyyMMddHHmmss}":m.PaymentNumber; e.Amount=m.Amount; e.Currency=m.Currency; e.PaymentMethod=m.PaymentMethod; e.PaymentDateUtc=m.PaymentDateUtc; e.Status=m.Status; e.Reference=m.Reference; e.Notes=m.Notes; if(!m.Id.HasValue)db.Payments.Add(e); db.AuditLogs.Add(new(){Action=m.Id.HasValue?"Zahlung geändert":"Zahlung erfasst",EntityName=nameof(Payment),EntityId=e.Id.ToString()}); await db.SaveChangesAsync(ct); }
    public async Task<IReadOnlyList<Invoice>> GetInvoicesAsync(CancellationToken ct)=>await db.Invoices.AsNoTracking().OrderByDescending(i=>i.InvoiceDateUtc).ToListAsync(ct); public Task<InvoiceDto> CreateInvoiceAsync(InvoiceFormModel m,CancellationToken ct)=>invoices.CreateAsync(m.CustomerId,m.SubscriptionId,m.NetAmount,ct); public Task MarkInvoicePaidAsync(Guid id,CancellationToken ct)=>Update<Invoice>(id,i=>i.Status=InvoiceStatus.Paid,"Rechnung bezahlt",ct);
    public async Task<IReadOnlyList<AuditLog>> GetAuditLogsAsync(CancellationToken ct)=>await db.AuditLogs.AsNoTracking().OrderByDescending(a=>a.CreatedAtUtc).Take(200).ToListAsync(ct); public async Task<IReadOnlyList<SystemSetting>> GetSettingsAsync(CancellationToken ct)=>await db.SystemSettings.AsNoTracking().OrderBy(s=>s.Key).ToListAsync(ct); public async Task SaveSettingAsync(Guid? id,string key,string value,string? description,CancellationToken ct){ var e=id.HasValue?await db.SystemSettings.FindAsync([id.Value],ct):new SystemSetting(); if(e is null)return; e.Key=key; e.Value=value; e.Description=description; e.UpdatedAtUtc=DateTime.UtcNow; if(!id.HasValue)db.SystemSettings.Add(e); await db.SaveChangesAsync(ct); }
    public async Task<IReadOnlyList<UserListModel>> GetUsersAsync(CancellationToken ct){ var list=await users.Users.AsNoTracking().OrderBy(u=>u.Email).ToListAsync(ct); var result=new List<UserListModel>(); foreach(var u in list) result.Add(new(){Id=u.Id,Email=u.Email??"",FirstName=u.FirstName,LastName=u.LastName,IsActive=u.IsActive,Roles=string.Join(", ",await users.GetRolesAsync(u))}); return result; } public async Task SaveUserAsync(UserFormModel m,CancellationToken ct){ var u=string.IsNullOrWhiteSpace(m.Id)?new ApplicationUser{UserName=m.Email,Email=m.Email,EmailConfirmed=true,CreatedAtUtc=DateTime.UtcNow}:await users.FindByIdAsync(m.Id); if(u is null)return; u.FirstName=m.FirstName; u.LastName=m.LastName; u.Email=m.Email; u.UserName=m.Email; u.IsActive=m.IsActive; if(string.IsNullOrWhiteSpace(m.Id)){ var r=await users.CreateAsync(u,m.Password); if(!r.Succeeded) throw new InvalidOperationException(string.Join("; ",r.Errors.Select(e=>e.Description))); } else await users.UpdateAsync(u); var roles=await users.GetRolesAsync(u); await users.RemoveFromRolesAsync(u,roles); await users.AddToRoleAsync(u,m.Role); } public async Task SetUserActiveAsync(string id,bool active,CancellationToken ct){ var u=await users.FindByIdAsync(id); if(u is null)return; u.IsActive=active; await users.UpdateAsync(u); }

    async Task Update<T>(Guid id, Action<T> change, string action, CancellationToken ct) where T:class { var e=await db.Set<T>().FindAsync([id],ct); if(e is null)return; change(e); db.AuditLogs.Add(new(){Action=action,EntityName=typeof(T).Name,EntityId=id.ToString()}); await db.SaveChangesAsync(ct); }
}
