using IptvManagement.Domain.Enums;

namespace IptvManagement.Application.DTOs;

public sealed class CustomerFormModel { public Guid? Id { get; set; } public string CustomerNumber { get; set; } = ""; public string FirstName { get; set; } = ""; public string LastName { get; set; } = ""; public string? CompanyName { get; set; } public string Email { get; set; } = ""; public string? Phone { get; set; } public string? Address { get; set; } public string? PostalCode { get; set; } public string? City { get; set; } public string Country { get; set; } = "AT"; public string? Notes { get; set; } public bool IsActive { get; set; } = true; public bool IsBlocked { get; set; } }
public sealed class CategoryFormModel { public Guid? Id { get; set; } public string Name { get; set; } = ""; public string? Description { get; set; } public int SortOrder { get; set; } public bool IsActive { get; set; } = true; }
public sealed class PackageFormModel { public Guid? Id { get; set; } public string Name { get; set; } = ""; public string? Description { get; set; } public decimal Price { get; set; } public string Currency { get; set; } = "EUR"; public int DurationInMonths { get; set; } = 1; public int MaxDevices { get; set; } = 1; public bool IsActive { get; set; } = true; public List<Guid> ChannelIds { get; set; } = []; }
public sealed class ChannelFormModel { public Guid? Id { get; set; } public string Name { get; set; } = ""; public string? Description { get; set; } public string StreamUrl { get; set; } = ""; public string? LogoUrl { get; set; } public Guid CategoryId { get; set; } public string CountryCode { get; set; } = "AT"; public string LanguageCode { get; set; } = "de"; public int SortOrder { get; set; } public bool IsActive { get; set; } = true; public bool IsPubliclyAvailable { get; set; } public string LicenseReference { get; set; } = ""; public DateTime? LicenseValidUntilUtc { get; set; } }
public sealed class SubscriptionFormModel { public Guid? Id { get; set; } public Guid CustomerId { get; set; } public Guid PackageId { get; set; } public string SubscriptionNumber { get; set; } = ""; public DateTime StartDateUtc { get; set; } = DateTime.UtcNow.Date; public int DurationInMonths { get; set; } = 12; public DateTime ExpirationDateUtc { get; set; } = DateTime.UtcNow.Date.AddMonths(12); public SubscriptionStatus Status { get; set; } = SubscriptionStatus.Active; public int MaxDevices { get; set; } = 1; public bool AutomaticRenewal { get; set; } }
public sealed class DeviceFormModel { public Guid? Id { get; set; } public Guid CustomerId { get; set; } public Guid SubscriptionId { get; set; } public string DeviceName { get; set; } = ""; public string DeviceIdentifier { get; set; } = ""; public DeviceType DeviceType { get; set; } = DeviceType.Unknown; public bool IsActive { get; set; } = true; public bool IsBlocked { get; set; } }
public sealed class PaymentFormModel { public Guid? Id { get; set; } public Guid CustomerId { get; set; } public Guid SubscriptionId { get; set; } public string PaymentNumber { get; set; } = ""; public decimal Amount { get; set; } public string Currency { get; set; } = "EUR"; public PaymentMethod PaymentMethod { get; set; } = PaymentMethod.BankTransfer; public DateTime PaymentDateUtc { get; set; } = DateTime.UtcNow; public PaymentStatus Status { get; set; } = PaymentStatus.Open; public string? Reference { get; set; } public string? Notes { get; set; } }
public sealed class InvoiceFormModel { public Guid? Id { get; set; } public Guid CustomerId { get; set; } public Guid SubscriptionId { get; set; } public decimal NetAmount { get; set; } public InvoiceStatus Status { get; set; } = InvoiceStatus.Issued; }
public sealed class UserFormModel { public string? Id { get; set; } public string FirstName { get; set; } = ""; public string LastName { get; set; } = ""; public string Email { get; set; } = ""; public string Password { get; set; } = ""; public string Role { get; set; } = "NurLesen"; public bool IsActive { get; set; } = true; }
public sealed class UserListModel { public string Id { get; set; } = ""; public string FirstName { get; set; } = ""; public string LastName { get; set; } = ""; public string Email { get; set; } = ""; public bool IsActive { get; set; } public string Roles { get; set; } = ""; }
