using IptvManagement.Domain.Enums;
namespace IptvManagement.Domain.Entities;
public class Customer { public Guid Id{get;set;}=Guid.NewGuid(); public string CustomerNumber{get;set;}=""; public string FirstName{get;set;}=""; public string LastName{get;set;}=""; public string? CompanyName{get;set;} public string Email{get;set;}=""; public string? Phone{get;set;} public string? Address{get;set;} public string? PostalCode{get;set;} public string? City{get;set;} public string Country{get;set;}="AT"; public string? Notes{get;set;} public bool IsActive{get;set;}=true; public bool IsBlocked{get;set;} public DateTime CreatedAtUtc{get;set;}=DateTime.UtcNow; public DateTime? UpdatedAtUtc{get;set;} public List<Subscription> Subscriptions{get;set;}=[]; public List<Device> Devices{get;set;}=[]; }
public class Subscription { public Guid Id{get;set;}=Guid.NewGuid(); public Guid CustomerId{get;set;} public Guid PackageId{get;set;} public string SubscriptionNumber{get;set;}=""; public DateTime StartDateUtc{get;set;} public DateTime ExpirationDateUtc{get;set;} public SubscriptionStatus Status{get;set;}=SubscriptionStatus.Draft; public int MaxDevices{get;set;} public string? PlaylistTokenHash{get;set;} public DateTime? TokenCreatedAtUtc{get;set;} public DateTime? LastRenewedAtUtc{get;set;} public bool AutomaticRenewal{get;set;} public DateTime CreatedAtUtc{get;set;}=DateTime.UtcNow; public DateTime? UpdatedAtUtc{get;set;} public Customer Customer{get;set;}=null!; public SubscriptionPackage Package{get;set;}=null!; public List<Device> Devices{get;set;}=[]; public bool IsUsable(DateTime utcNow)=>Status==SubscriptionStatus.Active && ExpirationDateUtc>utcNow; public void Renew(int months, DateTime utcNow){ if(months<=0) throw new ArgumentOutOfRangeException(nameof(months)); var baseDate=ExpirationDateUtc>utcNow?ExpirationDateUtc:utcNow; ExpirationDateUtc=baseDate.AddMonths(months); Status=SubscriptionStatus.Active; LastRenewedAtUtc=utcNow; UpdatedAtUtc=utcNow; } }
public class SubscriptionPackage { public Guid Id{get;set;}=Guid.NewGuid(); public string Name{get;set;}=""; public string? Description{get;set;} public decimal Price{get;set;} public string Currency{get;set;}="EUR"; public int DurationInMonths{get;set;}=1; public int MaxDevices{get;set;}=1; public bool IsActive{get;set;}=true; public DateTime CreatedAtUtc{get;set;}=DateTime.UtcNow; public DateTime? UpdatedAtUtc{get;set;} public List<PackageChannel> PackageChannels{get;set;}=[]; }
public class Device { public Guid Id{get;set;}=Guid.NewGuid(); public Guid CustomerId{get;set;} public Guid SubscriptionId{get;set;} public string DeviceName{get;set;}=""; public string DeviceIdentifierHash{get;set;}=""; public DeviceType DeviceType{get;set;} public string? LastIpAddress{get;set;} public DateTime FirstSeenAtUtc{get;set;}=DateTime.UtcNow; public DateTime? LastSeenAtUtc{get;set;} public bool IsActive{get;set;}=true; public bool IsBlocked{get;set;} public Customer Customer{get;set;}=null!; public Subscription Subscription{get;set;}=null!; }
public class Channel { public Guid Id{get;set;}=Guid.NewGuid(); public string Name{get;set;}=""; public string? Description{get;set;} public string StreamUrlEncrypted{get;set;}=""; public string? LogoUrl{get;set;} public Guid CategoryId{get;set;} public string CountryCode{get;set;}="AT"; public string LanguageCode{get;set;}="de"; public int SortOrder{get;set;} public bool IsActive{get;set;}=true; public bool IsPubliclyAvailable{get;set;} public string LicenseReference{get;set;}=""; public DateTime? LicenseValidUntilUtc{get;set;} public DateTime CreatedAtUtc{get;set;}=DateTime.UtcNow; public DateTime? UpdatedAtUtc{get;set;} public ChannelCategory Category{get;set;}=null!; public List<PackageChannel> PackageChannels{get;set;}=[]; public bool HasValidLicense(DateTime utcNow)=>IsPubliclyAvailable || LicenseValidUntilUtc is null || LicenseValidUntilUtc>utcNow; }
public class ChannelCategory { public Guid Id{get;set;}=Guid.NewGuid(); public string Name{get;set;}=""; public string? Description{get;set;} public int SortOrder{get;set;} public bool IsActive{get;set;}=true; public List<Channel> Channels{get;set;}=[]; }
public class PackageChannel { public Guid PackageId{get;set;} public Guid ChannelId{get;set;} public SubscriptionPackage Package{get;set;}=null!; public Channel Channel{get;set;}=null!; }
public class Payment { public Guid Id{get;set;}=Guid.NewGuid(); public Guid CustomerId{get;set;} public Guid SubscriptionId{get;set;} public string PaymentNumber{get;set;}=""; public decimal Amount{get;set;} public string Currency{get;set;}="EUR"; public PaymentMethod PaymentMethod{get;set;} public DateTime PaymentDateUtc{get;set;} public PaymentStatus Status{get;set;} public string? Reference{get;set;} public string? Notes{get;set;} public DateTime CreatedAtUtc{get;set;}=DateTime.UtcNow; }
public class Invoice { public Guid Id{get;set;}=Guid.NewGuid(); public Guid CustomerId{get;set;} public Guid SubscriptionId{get;set;} public string InvoiceNumber{get;set;}=""; public DateTime InvoiceDateUtc{get;set;} public DateTime DueDateUtc{get;set;} public decimal NetAmount{get;set;} public decimal TaxAmount{get;set;} public decimal GrossAmount{get;set;} public string Currency{get;set;}="EUR"; public InvoiceStatus Status{get;set;} public string? PdfFilePath{get;set;} public DateTime CreatedAtUtc{get;set;}=DateTime.UtcNow; }
public class AuditLog { public Guid Id{get;set;}=Guid.NewGuid(); public string? UserId{get;set;} public string Action{get;set;}=""; public string EntityName{get;set;}=""; public string? EntityId{get;set;} public string? OldValues{get;set;} public string? NewValues{get;set;} public string? IpAddress{get;set;} public DateTime CreatedAtUtc{get;set;}=DateTime.UtcNow; }
public class PlaylistAccessLog { public Guid Id{get;set;}=Guid.NewGuid(); public Guid? CustomerId{get;set;} public Guid? SubscriptionId{get;set;} public Guid? DeviceId{get;set;} public string? IpAddress{get;set;} public string? UserAgent{get;set;} public DateTime RequestedAtUtc{get;set;}=DateTime.UtcNow; public bool WasSuccessful{get;set;} public string? FailureReason{get;set;} }
public class SystemSetting { public Guid Id{get;set;}=Guid.NewGuid(); public string Key{get;set;}=""; public string Value{get;set;}=""; public string? Description{get;set;} public DateTime UpdatedAtUtc{get;set;}=DateTime.UtcNow; }
public class DeviceActivationCode { public Guid Id{get;set;}=Guid.NewGuid(); public Guid SubscriptionId{get;set;} public string CodeHash{get;set;}=""; public DateTime ExpiresAtUtc{get;set;} public DateTime CreatedAtUtc{get;set;}=DateTime.UtcNow; public DateTime? UsedAtUtc{get;set;} public bool IsUsed=>UsedAtUtc.HasValue; }
